describe('First5TestCases', () => {
  it('Signing up a new Account', () => {
    cy.visit('https://automationexercise.com/login')
    cy.get('[data-qa="signup-name"]')
    .type('Jonathan')
    cy.get('[data-qa="signup-email"]')
    .type('jona@than.com')
    cy.get('[data-qa="signup-button"]')
    .click()
    cy.get('[id="id_gender2"]')
    cy.get('[id="id_gender1"]')
    .click()
    cy.get('[data-qa="password"]')
    .type ('ichbinjonathan536')
    cy.get('[data-qa="days"]')
    .select('24')
    cy.get('[data-qa="months"]')
    .select('9')
    cy.get('[data-qa="years"]')
    .select('2021')
    cy.get('[class="checkbox"]')
    .click({multiple: true })
     cy.get('[data-qa="first_name"]')
    .type('Jonathan')
    cy.get('[data-qa="last_name"]')
    .type('Schneider')
    cy.get('[data-qa="company"]')
    .type('Regenburg')
    cy.get('[data-qa="address"]')
    .type('Koenigsforst 3')
    cy.get('[data-qa="country"]')
    .select('Australia')
    cy.get('[data-qa="state"]')
    .type('unicorn-island')
    cy.get('[data-qa="city"]')
    .type('Rotterdam')
    cy.get('[data-qa="zipcode"]')
    .type('511')
    cy.get('[data-qa="mobile_number"]')
    .type('519285918571')
    cy.get('[data-qa="create-account"]')
    .click()
    cy.get('[data-qa="account-created"]').should('contain',"Account Created!")
    })

    it('LoggingIn,InvalidCredentials', () => {
    cy.visit('https://automationexercise.com/login')
    cy.get('[data-qa="login-email"]')
    .type('jonas@doof.com')
    cy.get('[data-qa="login-password"]')
    .type ('jonasistcool787')
    cy.get('[data-qa="login-button')
    .click()
    cy.contains('Your email or password is incorrect!').should('contain',"Your email or password is incorrect!")
    })

    it('LogInLogOut', () => {
    cy.visit('https://automationexercise.com/login')
    cy.get('[data-qa="login-email"]')
    .type('jona@than.com')
    cy.get('[data-qa="login-password"]')
    .type ('ichbinjonathan536')
    cy.get('[data-qa="login-button"]')
    .click()
    cy.get('.nav').should('contain',"Logout")
    cy.contains('Logout')
    .click()
    cy.get('[class="login-form"]').should('contain',"Login to your account")
    })

    it('SignupWithExistingAccount', () => {
    cy.visit('https://automationexercise.com/login')
    cy.get('[data-qa="signup-name"]')
    .type('Jonathan')
    cy.get('[data-qa="signup-email"]')
    .type('jona@than.com')
    cy.get('[data-qa="signup-button"]')
    .click()
    cy.contains('Email Address already exist!').should('contain',"Email Address already exist!")
    })

    it('LoggingIn,ValidCredentials', () => {
    cy.visit('https://automationexercise.com/login')
    cy.get('[data-qa="login-email"]')
    .type('jona@than.com')
    cy.get('[data-qa="login-password"]')
    .type ('ichbinjonathan536')
    cy.get('[data-qa="login-button"]')
    .click()
    cy.get('.nav').should('contain',"Logout")
    cy.contains('Delete Account')
    .click()
    cy.get('[data-qa="account-deleted"]').should('contain',"Account Deleted!")
    cy.get('[data-qa="continue-button"]')
    .click()
    })
})