describe('TestCases', () => {
  it('ContactUsForm', () => {
    cy.visit('http://automationexercise.com')
    cy.contains('Contact us')
    .click()
    cy.get('[data-qa="name"]')
    .type('Jonathan')    
    cy.get('[data-qa="email"]')
    .type('jona@than.com')
    cy.get('[data-qa="subject"]')
    .type('Job Interview')
    cy.get('[data-qa="message"]')
    .type('Hello, I want to talk to you about my recent Job Interview! Hope to hear from you again. Greetings Jonathan')
    cy.get('input[type=file]').selectFile('/Users/alexandergschwendtner/Documents/cypress-learning/TesterTextToUpload.txt')
    cy.get('[data-qa="submit-button"]')
    .click()
    cy.contains('Success! Your details have been submitted successfully.').should('contain',"Success! Your details have been submitted successfully.")
    cy.contains('Home')
    .click()
    cy.get('h2').should('contain',"Features Items")
  })

  it('TestCasePage', () => {
    cy.visit('http://automationexercise.com')
    cy.get('h2').should('contain',"Features Items")
    cy.contains('Test Cases')
    .click()
    cy.get('.title.text-center').should('contain',"Test Cases")
  })

  it('ProductViewing', () => {
    cy.visit('http://automationexercise.com')
    cy.get('h2').should('contain',"Features Items")
    cy.contains('Products')
    .click()
    cy.get('[href="/product_details/1"]')
    .click()
    cy.get('.product-information').should('contain',"Blue Top","Category","Price","Availability","Condition","Brand")
  })

    it('SearchProduct', () => {
    cy.visit('http://automationexercise.com')
    cy.get('h2').should('contain',"Features Items")
    cy.contains('Products')
    .click()
    cy.get('.title.text-center').should('contain',"All Products")
    cy.get('#search_product')
    .type('Sleeveless Unicorn')
    cy.get('#submit_search')
    .click()
    cy.get('.productinfo.text-center').should('contain',"Sleeveless Unicorn")
  })

    it('SubscriptionHomePage', () => {
    cy.visit('http://automationexercise.com')
    cy.get('h2').should('contain',"Features Items")
    cy.get('#susbscribe_email')
    .type('jona@than.com')
    cy.get('#subscribe')
    .click()
    cy.contains('You have been successfully subscribed!').should('contain',"You have been successfully subscribed!")
  })

    it('SubscriptionCartPage', () => {
    cy.visit('http://automationexercise.com')
    cy.get('h2').should('contain',"Features Items")
    cy.contains('Cart')
    .click()
    cy.get('#susbscribe_email')
    .type('jona@than.com')
    cy.get('#subscribe')
    .click()
    cy.contains('You have been successfully subscribed!').should('contain',"You have been successfully subscribed!")
    })

    it('AddingProductsToCart', () => {
    cy.visit('http://automationexercise.com')
    cy.get('h2').should('contain',"Features Items")
    cy.contains('Products')
    .click()
    cy.get('[data-product-id="2"]').first().click()
    cy.contains('Continue Shopping')
    .click()
    cy.get('[data-product-id="1"]').first().click()
    cy.contains('View Cart')
    .click()
    cy.get('.cart_description').should('contain',"Men Tshirt").should('contain',"Blue Top")
    cy.get('.cart_price').should('contain',"400","500")
    cy.get('.cart_quantity').should('contain',"1")
    })

    it('VerifyProductQuantity', () => {
    cy.visit('http://automationexercise.com')
    cy.get('h2').should('contain',"Features Items")
    cy.get('[href="/product_details/1"]')
    .click()
    cy.get('label').should('contain',"Quantity")
    cy.get('#quantity')
    .clear().type(4)
    cy.contains('Add to cart')
    .click()
    cy.contains('View Cart')
    .click()
    cy.get('.cart_description').should('contain',"Blue Top")
    cy.get('.cart_quantity').should('contain',"4")
    })
})